export enum AgroproveerRoutes {
    LOGIN = 'login',
    REGISTER = 'register',
    HOME = 'home',
    ABOUT = 'about',
    CART = 'cart',
    CHECKOUT = 'checkout',
    CHECKOUT_SUCCESS = 'checkout/success',
    MERCADO = 'market',
    ADMINPRODUCTOS = 'adminproducts',
    ADMINCATEGORIAS = 'admincategories',
    LOGOUT = 'logout',
    PERFIL = 'profile',
    PRODUCTOS = 'products',
    CATEGORIAS = 'categories',
    CARRITO = 'cart',
    MYPRODUCTS = 'my-products',
    BUSCAR_ORDEN = 'search-order',
}