version: '3.8'

services:
  agroproveer_database:
    image: postgres:latest
    container_name: agroproveer-database
    environment:
      POSTGRES_DB: agroproveer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5431:5432"
  
    